/* DO NOT EDIT THIS FILE - it is machine generated */
#include <hmwk1_cis350_helloworld_MainActivity.h>

/*
 * Class:     hmwk1_cis350_helloworld_MainActivity
 * Method:    HelloJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hmwk1_cis350_helloworld_MainActivity_HelloJni
  (JNIEnv * env, jobject object){
    return (*env)->NewStringUTF(env, "Hello from native code!");


}


