/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hmwk1_cis350_helloworld_MainActivity */

#ifndef _Included_hmwk1_cis350_helloworld_MainActivity
#define _Included_hmwk1_cis350_helloworld_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hmwk1_cis350_helloworld_MainActivity
 * Method:    HelloJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_hmwk1_cis350_helloworld_MainActivity_HelloJni
  (JNIEnv *, jobject);

/*
 * Class:     hmwk1_cis350_helloworld_MainActivity
 * Method:    changeDogAge
 * Signature: (ILhmwk1/cis350/helloworld/Dog;)Lhmwk1/cis350/helloworld/Dog;
 */
JNIEXPORT jint JNICALL Java_hmwk1_cis350_helloworld_MainActivity_changeDogAge
  (JNIEnv *, jobject, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
